//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBank.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CashTransactions
    {
        [Required(ErrorMessage = "This Line Can't Be Null\n\n")]
        public int ID { get; set; }
        [Required(ErrorMessage = "This Line Can't Be Null\n\n")]
        public int CusID { get; set; }
        [Required(ErrorMessage = "This Line Can't Be Null\n\n")]
        public int ConsID { get; set; }
        [Required(ErrorMessage = "This Line Can't Be Null\n\n")]
        public bool Deposit_Withdraw { get; set; }
        [Required(ErrorMessage = "This Line Can't Be Null\n\n")]
        public int Amount { get; set; }
        [Required(ErrorMessage = "This Line Can't Be Null\n\n")]
        [MaxLength(3, ErrorMessage = "Currency Abbrevation Cannot Be Longer Than 3 Characters\n\n")]
        [RegularExpression(@"([A-Za-z]+)", ErrorMessage = "Currency Can Only Contain Alphabetical Characters\n\n")]
        public string Currency { get; set; }
    
        public virtual Consultant Consultant { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
