//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBank.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CryptoTransactions
    {
        [Required(ErrorMessage = "This Line Can't Be Null")]
        public int ID { get; set; }
        [Required(ErrorMessage = "This Line Can't Be Null")]
        public Nullable<int> CusID { get; set; }
        [Required(ErrorMessage = "This Line Can't Be Null")]
        public Nullable<int> ConsID { get; set; }
        [Required(ErrorMessage = "This Line Can't Be Null")]
        public Nullable<bool> Buy_Sell { get; set; }
        [Required(ErrorMessage = "This Line Can't Be Null")]
        public Nullable<int> Amount { get; set; }
        [Required(ErrorMessage = "This Line Can't Be Null")]
        [MaxLength(3, ErrorMessage = "Currency Abbrevation Cannot Be Longer Than 3 Characters")]
        [RegularExpression(@"([A-Za-z]+)", ErrorMessage = "Currency Can Only Contain Alphabetical Characters ")]
        public string CryptoAcr { get; set; }
    
        public virtual Consultant Consultant { get; set; }
        public virtual Cryptos Cryptos { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
