//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBank.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cryptos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cryptos()
        {
            this.CryptoTransactions = new HashSet<CryptoTransactions>();
            this.OwnedCryptos = new HashSet<OwnedCryptos>();
        }
        [Required(ErrorMessage = "This Line Can't Be Null")]
        public string Acronym { get; set; }
        [Required(ErrorMessage = "This Line Can't Be Null")]
        public string FullName { get; set; }
        [Required(ErrorMessage = "This Line Can't Be Null")]
        public Nullable<int> Value_ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CryptoTransactions> CryptoTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OwnedCryptos> OwnedCryptos { get; set; }
    }
}
