//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBank.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Deposit
    {
        [Required(ErrorMessage = "This Line Can't Be Null")]
        public int CusID { get; set; }
        [Required(ErrorMessage = "This Line Can't Be Null")]
        public decimal Cash { get; set; }
        [Required(ErrorMessage = "This Line Can't Be Null")]
        [MaxLength(3, ErrorMessage = "Currency Abbrevation Cannot Be Longer Than 3 Characters")]
        [RegularExpression(@"([A-Za-z]+)", ErrorMessage = "Currency Can Only Contain Alphabetical Characters ")]
        public string Currency { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
